In [1]:
import pandas as pd

In [2]:
d = pd.read_csv('weather.csv')

In [3]:
d.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [4]:
myDict = {
    'dates': ['02-01-18', '03-01-18', '04-01-18', '05-01-18', '06-01-18'],
    'day': ['sunny', 'rainy', 'hot', 'sunny', 'hot'],
    'wind-speed': [12, 34, 45, 56, 67],
    'temp': [45, 46, 47, 48, 49]
}
df = pd.DataFrame(myDict)
df

      dates    day  wind-speed  temp
0  02-01-18  sunny          12    45
1  03-01-18  rainy          34    46
2  04-01-18    hot          45    47
3  05-01-18  sunny          56    48
4  06-01-18    hot          67    49

In [11]:
df['day']

0    sunny
1    rainy
2      hot
3    sunny
4      hot
Name: day, dtype: object

In [12]:
df['temp']

0    45
1    46
2    47
3    48
4    49
Name: temp, dtype: int64

In [16]:
df[['day', 'temp', 'wind-speed']]

     day  temp  wind-speed
0  sunny    45          12
1  rainy    46          34
2    hot    47          45
3  sunny    48          56
4    hot    49          67

In [17]:
df.shape

(5, 4)

In [18]:
d.describe()

,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars)
count,31669.000000,31669.000000,31669.000000,31669.000000,31669.000000,31669.000000,31669.0,31669.000000
mean,11.828309,10.697191,0.717960,10.861736,191.138527,10.101487,0.0,1000.486637
std,9.702414,10.822627,0.192991,6.964968,106.222524,3.756646,0.0,129.776375
min,-16.666667,-24.233333,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,4.383333,1.983333,0.590000,5.796000,120.000000,9.708300,0.0,1011.820000
50%,11.577778,11.577778,0.770000,9.885400,189.000000,9.982000,0.0,1016.650000
75%,18.888889,18.888889,0.870000,14.248500,290.000000,11.270000,0.0,1021.790000
max,39.905556,38.377778,1.000000,63.852600,359.000000,16.100000,0.0,1046.380000

In [22]:
d1 = d[d['Temperature (C)'] > 9]
d1

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
5,2006-04-01 05:00:00.000 +0200,Partly Cloudy,rain,9.222222,7.111111,0.85,13.9587,258.0,14.9569,0.0,1016.66,Partly cloudy throughout the day.
8,2006-04-01 08:00:00.000 +0200,Partly Cloudy,rain,10.822222,10.822222,0.82,11.3183,259.0,9.9820,0.0,1017.37,Partly cloudy throughout the day.
9,2006-04-01 09:00:00.000 +0200,Partly Cloudy,rain,13.772222,13.772222,0.72,12.5258,279.0,9.9820,0.0,1017.22,Partly cloudy throughout the day.
10,2006-04-01 10:00:00.000 +0200,Partly Cloudy,rain,16.016667,16.016667,0.67,17.5651,290.0,11.2056,0.0,1017.42,Partly cloudy throughout the day.
11,2006-04-01 11:00:00.000 +0200,Partly Cloudy,rain,17.144444,17.144444,0.54,19.7869,316.0,11.4471,0.0,1017.74,Partly cloudy throughout the day.
12,2006-04-01 12:00:00.000 +0200,Partly Cloudy,rain,17.800000,17.800000,0.55,21.9443,281.0,11.2700,0.0,1017.59,Partly cloudy throughout the day.
13,2006-04-01 13:00:00.000 +0200,Partly Cloudy,rain,17.333333,17.333333,0.51,20.6885,289.0,11.2700,0.0,1017.48,Partly cloudy throughout the day.
14,2006-04-01 14:00:00.000 +0200,Partly Cloudy,rain,18.877778,18.877778,0.47,15.3755,262.0,11.4471,0.0,1017.17,Partly cloudy throughout the day.
15,2006-04-01 15:00:00.000 +0200,Partly Cloudy,rain,18.911111,18.911111,0.46,10.4006,288.0,11.2700,0.0,1016.47,Partly cloudy throughout the day.
16,2006-04-01 16:00:00.000 +0200,Partly Cloudy,rain,15.388889,15.388889,0.60,14.4095,251.0,11.2700,0.0,1016.15,Partly cloudy throughout the day.
17,2006-04-01 17:00:00.000 +0200,Mostly Cloudy,rain,15.550000,15.550000,0.63,11.1573,230.0,11.4471,0.0,1016.17,Partly cloudy throughout the day.
18,2006-04-01 18:00:00.000 +0200,Mostly Cloudy,rain,14.255556,14.255556,0.69,8.5169,163.0,11.2056,0.0,1015.82,Partly cloudy throughout the day.
19,2006-04-01 19:00:00.000 +0200,Mostly Cloudy,rain,13.144444,13.144444,0.70,7.6314,139.0,11.2056,0.0,1015.83,Partly cloudy throughout the day.
20,2006-04-01 20:00:00.000 +0200,Mostly Cloudy,rain,11.550000,11.550000,0.77,7.3899,147.0,11.0285,0.0,1015.85,Partly cloudy throughout the day.
21,2006-04-01 21:00:00.000 +0200,Mostly Cloudy,rain,11.183333,11.183333,0.76,4.9266,160.0,9.9820,0.0,1015.77,Partly cloudy throughout the day.
22,2006-04-01 22:00:00.000 +0200,Partly Cloudy,rain,10.116667,10.116667,0.79,6.6493,163.0,15.8263,0.0,1015.40,Partly cloudy throughout the day.
23,2006-04-01 23:00:00.000 +0200,Mostly Cloudy,rain,10.200000,10.200000,0.77,3.9284,152.0,14.9569,0.0,1015.51,Partly cloudy throughout the day.
24,2006-04-10 00:00:00.000 +0200,Partly Cloudy,rain,10.422222,10.422222,0.62,16.9855,150.0,15.8263,0.0,1014.40,Mostly cloudy throughout the day.
25,2006-04-10 01:00:00.000 +0200,Partly Cloudy,rain,9.911111,7.566667,0.66,17.2109,149.0,15.8263,0.0,1014.20,Mostly cloudy throughout the day.
26,2006-04-10 02:00:00.000 +0200,Mostly Cloudy,rain,11.183333,11.183333,0.80,10.8192,163.0,14.9569,0.0,1008.71,Mostly cloudy throughout the day.
32,2006-04-10 08:00:00.000 +0200,Mostly Cloudy,rain,9.872222,7.933333,0.78,13.7494,160.0,9.9820,0.0,1014.24,Mostly cloudy throughout the day.
33,2006-04-10 09:00:00.000 +0200,Mostly Cloudy,rain,12.222222,12.222222,0.72,15.6331,150.0,9.9820,0.0,1014.25,Mostly cloudy throughout the day.
34,2006-04-10 10:00:00.000 +0200,Mostly Cloudy,rain,15.094444,15.094444,0.61,17.5490,151.0,9.9820,0.0,1013.96,Mostly cloudy throughout the day.
35,2006-04-10 11:00:00.000 +0200,Mostly Cloudy,rain,17.355556,17.355556,0.52,22.7815,169.0,9.9820,0.0,1013.85,Mostly cloudy throughout the day.
36,2006-04-10 12:00:00.000 +0200,Mostly Cloudy,rain,19.005556,19.005556,0.46,23.8924,169.0,9.9820,0.0,1013.04,Mostly cloudy throughout the day.
37,2006-04-10 13:00:00.000 +0200,Mostly Cloudy,rain,20.044444,20.044444,0.40,28.3682,170.0,9.9820,0.0,1012.22,Mostly cloudy throughout the day.
38,2006-04-10 14:00:00.000 +0200,Mostly Cloudy,rain,21.050000,21.050000,0.40,26.9031,187.0,10.3523,0.0,1011.44,Mostly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
31413,2009-06-09 21:00:00.000 +0200,Partly Cloudy,rain,22.222222,22.222222,0.55,9.6600,180.0,9.9820,0.0,1014.50,Partly cloudy throughout the day.
31414,2009-06-09 22:00:00.000 +0200,Partly Cloudy,rain,21.666667,21.666667,0.59,6.4400,170.0,16.1000,0.0,1015.00,Partly cloudy throughout the day.
31415,2009-06-09 23:00:00.000 +0200,Partly Cloudy,rain,21.372222,21.372222,0.58,6.6010,178.0,15.5204,0.0,1015.11,Partly cloudy throughout the day.
31427,2009-03-01 11:00:00.000 +0100,Partly Cloudy,rain,11.111111,11.111111,0.71,8.0500,160.0,11.2700,0.0,1017.40,Foggy in the morning.
31428,2009-03-01 12:00:00.000 +0100,Partly Cloudy,rain,12.222222,12.222222,0.61,11.2700,150.0,11.2700,0.0,1016.90,Foggy in the morning.
31429,2009-03-01 13:00:00.000 +0100,Mostly Cloudy,rain,12.866667,12.866667,0.57,13.2503,162.0,10.3684,0.0,1016.04,Foggy in the morning.
31430,2009-03-01 14:00:00.000 +0100,Mostly Cloudy,rain,12.777778,12.777778,0.59,14.4900,100.0,11.2700,0.0,1015.40,Foggy in the morning.
31431,2009-03-01 15:00:00.000 +0100,Mostly Cloudy,rain,12.777778,12.777778,0.69,16.1000,110.0,9.9820,0.0,1015.00,Foggy in the morning.
31432,2009-03-01 16:00:00.000 +0100,Mostly Cloudy,rain,12.533333,12.533333,0.63,12.9605,95.0,10.3684,0.0,1015.13,Foggy in the morning.
31433,2009-03-01 17:00:00.000 +0100,Mostly Cloudy,rain,10.555556,10.555556,0.77,17.7100,80.0,15.1340,0.0,1015.00,Foggy in the morning.
31434,2009-03-01 18:00:00.000 +0100,Mostly Cloudy,rain,10.000000,7.622222,0.77,17.7100,90.0,9.9820,0.0,0.00,Foggy in the morning.
31453,2009-03-10 13:00:00.000 +0100,Mostly Cloudy,rain,9.933333,6.788889,0.50,26.0337,303.0,11.4471,0.0,1015.82,Partly cloudy until evening and breezy overnight.
31454,2009-03-10 14:00:00.000 +0100,Breezy and Partly Cloudy,rain,10.000000,6.344444,0.54,33.8100,300.0,11.2700,0.0,1015.30,Partly cloudy until evening and breezy overnight.
31455,2009-03-10 15:00:00.000 +0100,Partly Cloudy,rain,10.000000,6.661111,0.50,28.9800,300.0,11.2700,0.0,1015.10,Partly cloudy until evening and breezy overnight.
31456,2009-03-10 16:00:00.000 +0100,Partly Cloudy,rain,9.811111,7.550000,0.46,16.2127,318.0,11.4471,0.0,1015.22,Partly cloudy until evening and breezy overnight.
31502,2009-03-12 14:00:00.000 +0100,Partly Cloudy,rain,10.000000,7.161111,0.50,22.5400,320.0,11.2700,0.0,1019.50,Partly cloudy throughout the day.
31526,2009-03-13 14:00:00.000 +0100,Breezy and Partly Cloudy,rain,10.000000,6.344444,0.66,33.8100,280.0,11.2700,0.0,1011.80,Mostly cloudy throughout the day.
31552,2009-03-14 16:00:00.000 +0100,Partly Cloudy,rain,9.844444,9.077778,0.42,6.9069,11.0,11.4471,0.0,1021.27,Partly cloudy starting overnight continuing un...
31573,2009-03-15 13:00:00.000 +0100,Mostly Cloudy,rain,10.088889,10.088889,0.46,14.5544,141.0,10.3684,0.0,1022.57,Mostly cloudy starting overnight.
31574,2009-03-15 14:00:00.000 +0100,Mostly Cloudy,rain,11.111111,11.111111,0.46,8.0500,190.0,9.9820,0.0,1022.10,Mostly cloudy starting overnight.
31575,2009-03-15 15:00:00.000 +0100,Overcast,rain,11.111111,11.111111,0.43,8.0500,200.0,9.9820,0.0,1021.90,Mostly cloudy starting overnight.
31576,2009-03-15 16:00:00.000 +0100,Overcast,rain,9.044444,7.138889,0.57,12.2038,276.0,11.4471,0.0,1022.06,Mostly cloudy starting overnight.
31594,2009-03-16 10:00:00.000 +0100,Mostly Cloudy,rain,9.894444,6.544444,0.71,28.6902,320.0,11.0768,0.0,1025.08,Mostly cloudy throughout the day.
31595,2009-03-16 11:00:00.000 +0100,Mostly Cloudy,rain,10.000000,6.661111,0.71,28.9800,330.0,11.2700,0.0,1024.90,Mostly cloudy throughout the day.
31596,2009-03-16 12:00:00.000 +0100,Mostly Cloudy,rain,11.111111,11.111111,0.66,25.7600,330.0,11.2700,0.0,1024.80,Mostly cloudy throughout the day.
31597,2009-03-16 13:00:00.000 +0100,Partly Cloudy,rain,12.205556,12.205556,0.57,24.7618,330.0,11.4471,0.0,1024.42,Mostly cloudy throughout the day.
31598,2009-03-16 14:00:00.000 +0100,Partly Cloudy,rain,12.777778,12.777778,0.59,27.3700,320.0,11.2700,0.0,1023.70,Mostly cloudy throughout the day.
31599,2009-03-16 15:00:00.000 +0100,Partly Cloudy,rain,12.777778,12.777778,0.51,25.7600,320.0,11.2700,0.0,1023.20,Mostly cloudy throughout the day.
31644,2009-03-18 12:00:00.000 +0100,Windy,rain,10.000000,5.733333,0.41,45.0800,330.0,9.9820,0.0,0.00,Partly cloudy starting overnight continuing un...
31645,2009-03-18 13:00:00.000 +0100,Windy and Mostly Cloudy,rain,9.811111,5.722222,0.34,40.2500,312.0,10.3684,0.0,1019.40,Partly cloudy starting overnight continuing un...

In [23]:
d1.shape

(18308, 12)

In [24]:
df

      dates    day  wind-speed  temp
0  02-01-18  sunny          12    45
1  03-01-18  rainy          34    46
2  04-01-18    hot          45    47
3  05-01-18  sunny          56    48
4  06-01-18    hot          67    49

In [25]:
df.set_index('dates', inplace = True)

In [26]:
df

            day  wind-speed  temp
dates
02-01-18  sunny          12    45
03-01-18  rainy          34    46
04-01-18    hot          45    47
05-01-18  sunny          56    48
06-01-18    hot          67    49

In [27]:
df.loc['04-01-18']

day           hot
wind-speed     45
temp           47
Name: 04-01-18, dtype: object

In [28]:
df.iloc[4]

day           hot
wind-speed     67
temp           49
Name: 06-01-18, dtype: object

In [29]:
df.iloc[0:3]

            day  wind-speed  temp
dates
02-01-18  sunny          12    45
03-01-18  rainy          34    46
04-01-18    hot          45    47

In [30]:
df.reset_index()

      dates    day  wind-speed  temp
0  02-01-18  sunny          12    45
1  03-01-18  rainy          34    46
2  04-01-18    hot          45    47
3  05-01-18  sunny          56    48
4  06-01-18    hot          67    49